In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./clean/llm_classification_results_merged.csv')

In [4]:
df['classification'].value_counts()

classification
SUPPORTS           91596
NOT ENOUGH INFO    29160
REFUTES            24692
Name: count, dtype: int64

In [5]:
df['classification'].count()

np.int64(145448)

In [6]:
len(df)

145449

In [7]:
df

,index,claim,classification
0,0,Nikolaj Coster-Waldau worked with the Fox Broa...,SUPPORTS
1,1,Roman Atwood is a content creator.,NOT ENOUGH INFO
2,2,"History of art includes architecture, dance, s...",SUPPORTS
3,3,Adrienne Bailon is an accountant.,REFUTES
4,4,System of a Down briefly disbanded in limbo.,REFUTES
...,...,...,...
145444,145444,Led Zeppelin released an eponymous debut album...,REFUTES
145445,145445,Taal was romantic.,SUPPORTS
145446,145446,Her stars American actress Rooney Mara.,SUPPORTS
145447,145447,J. R. R. Tolkien created Gimli.,SUPPORTS
145448,145448,Susan Sarandon is an award winner.,SUPPORTS

In [18]:
df = df.drop_duplicates('claim')

In [23]:
len(df)

135545

In [19]:
import json
facts = json.load(open('claim_retrieved_docs_bm25.json','r'))

facts_df = pd.DataFrame(facts)

In [24]:
facts_df = facts_df.drop_duplicates('claim')
facts_df

,claim_id,claim,retrieved_documents
0,0,Nikolaj Coster-Waldau worked with the Fox Broa...,"[{'doc_id': 'Nukaaka_Coster-Waldau', 'text': '..."
1,1,Roman Atwood is a content creator.,"[{'doc_id': 'Bedside_Press', 'text': '{ ""id""..."
2,2,"History of art includes architecture, dance, s...","[{'doc_id': 'History_of_art', 'text': '{ ""id..."
3,3,Adrienne Bailon is an accountant.,"[{'doc_id': 'Adrienne_Bailon', 'text': '{ ""i..."
4,4,System of a Down briefly disbanded in limbo.,"[{'doc_id': 'System_of_a_Down', 'text': '{ ""..."
...,...,...,...
145443,145443,Sarah Michelle Gellar was in a movie.,"[{'doc_id': 'Gellar', 'text': '{ ""id"" : ""Gel..."
145444,145444,Led Zeppelin released an eponymous debut album...,"[{'doc_id': 'Led_Zeppelin_-LRB-album-RRB-', 't..."
145445,145445,Taal was romantic.,"[{'doc_id': 'Taal_-LRB-film-RRB-', 'text': '{ ..."
145446,145446,Her stars American actress Rooney Mara.,"[{'doc_id': 'Ann_Mara', 'text': '{ ""id"" : ""A..."
145447,145447,J. R. R. Tolkien created Gimli.,"[{'doc_id': 'Gimli_-LRB-Middle-earth-RRB-', 't..."

In [25]:
merged_df = pd.merge(facts_df, df, on='claim')

In [26]:
merged_df

,claim_id,claim,retrieved_documents,index,classification
0,0,Nikolaj Coster-Waldau worked with the Fox Broa...,"[{'doc_id': 'Nukaaka_Coster-Waldau', 'text': '...",0,SUPPORTS
1,1,Roman Atwood is a content creator.,"[{'doc_id': 'Bedside_Press', 'text': '{ ""id""...",1,NOT ENOUGH INFO
2,2,"History of art includes architecture, dance, s...","[{'doc_id': 'History_of_art', 'text': '{ ""id...",2,SUPPORTS
3,3,Adrienne Bailon is an accountant.,"[{'doc_id': 'Adrienne_Bailon', 'text': '{ ""i...",3,REFUTES
4,4,System of a Down briefly disbanded in limbo.,"[{'doc_id': 'System_of_a_Down', 'text': '{ ""...",4,REFUTES
...,...,...,...,...,...
135540,145443,Sarah Michelle Gellar was in a movie.,"[{'doc_id': 'Gellar', 'text': '{ ""id"" : ""Gel...",145443,SUPPORTS
135541,145444,Led Zeppelin released an eponymous debut album...,"[{'doc_id': 'Led_Zeppelin_-LRB-album-RRB-', 't...",145444,REFUTES
135542,145445,Taal was romantic.,"[{'doc_id': 'Taal_-LRB-film-RRB-', 'text': '{ ...",145445,SUPPORTS
135543,145446,Her stars American actress Rooney Mara.,"[{'doc_id': 'Ann_Mara', 'text': '{ ""id"" : ""A...",145446,SUPPORTS
135544,145447,J. R. R. Tolkien created Gimli.,"[{'doc_id': 'Gimli_-LRB-Middle-earth-RRB-', 't...",145447,SUPPORTS

In [31]:
# Merge label results

f = open('train.jsonl','r')
l = f.readlines()
res =[ ]
for l_ in l:
    res.append(json.loads(l_))

In [32]:
gt_data = pd.DataFrame(res)

In [33]:
gt_data

,id,verifiable,label,claim,evidence
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [..."
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271..."
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]"
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]"
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]"
...,...,...,...,...,...
145444,75062,VERIFIABLE,REFUTES,Led Zeppelin released an eponymous debut album...,"[[[91851, 104659, Led_Zeppelin, 6], [91851, 10..."
145445,149256,VERIFIABLE,SUPPORTS,Taal was romantic.,"[[[292586, 285327, Taal_-LRB-film-RRB-, 0]], [..."
145446,13287,VERIFIABLE,SUPPORTS,Her stars American actress Rooney Mara.,"[[[28520, 34848, Her_-LRB-film-RRB-, 3], [2852..."
145447,13114,VERIFIABLE,SUPPORTS,J. R. R. Tolkien created Gimli.,"[[[28359, 34669, Gimli_-LRB-Middle-earth-RRB-,..."
145448,152180,VERIFIABLE,SUPPORTS,Susan Sarandon is an award winner.,"[[[176133, 189101, Susan_Sarandon, 1]], [[1761..."

In [35]:
merged_df = pd.merge(gt_data, merged_df, on='claim')
merged_df

,id,verifiable,label,claim,evidence,claim_id,retrieved_documents,index,classification
0,75397,VERIFIABLE,SUPPORTS,Nikolaj Coster-Waldau worked with the Fox Broa...,"[[[92206, 104971, Nikolaj_Coster-Waldau, 7], [...",0,"[{'doc_id': 'Nukaaka_Coster-Waldau', 'text': '...",0,SUPPORTS
1,150448,VERIFIABLE,SUPPORTS,Roman Atwood is a content creator.,"[[[174271, 187498, Roman_Atwood, 1]], [[174271...",1,"[{'doc_id': 'Bedside_Press', 'text': '{ ""id""...",1,NOT ENOUGH INFO
2,214861,VERIFIABLE,SUPPORTS,"History of art includes architecture, dance, s...","[[[255136, 254645, History_of_art, 2]]]",2,"[{'doc_id': 'History_of_art', 'text': '{ ""id...",2,SUPPORTS
3,156709,VERIFIABLE,REFUTES,Adrienne Bailon is an accountant.,"[[[180804, 193183, Adrienne_Bailon, 0]]]",3,"[{'doc_id': 'Adrienne_Bailon', 'text': '{ ""i...",3,REFUTES
4,83235,NOT VERIFIABLE,NOT ENOUGH INFO,System of a Down briefly disbanded in limbo.,"[[[100277, None, None, None]]]",4,"[{'doc_id': 'System_of_a_Down', 'text': '{ ""...",4,REFUTES
...,...,...,...,...,...,...,...,...,...
145444,75062,VERIFIABLE,REFUTES,Led Zeppelin released an eponymous debut album...,"[[[91851, 104659, Led_Zeppelin, 6], [91851, 10...",145444,"[{'doc_id': 'Led_Zeppelin_-LRB-album-RRB-', 't...",145444,REFUTES
145445,149256,VERIFIABLE,SUPPORTS,Taal was romantic.,"[[[292586, 285327, Taal_-LRB-film-RRB-, 0]], [...",145445,"[{'doc_id': 'Taal_-LRB-film-RRB-', 'text': '{ ...",145445,SUPPORTS
145446,13287,VERIFIABLE,SUPPORTS,Her stars American actress Rooney Mara.,"[[[28520, 34848, Her_-LRB-film-RRB-, 3], [2852...",145446,"[{'doc_id': 'Ann_Mara', 'text': '{ ""id"" : ""A...",145446,SUPPORTS
145447,13114,VERIFIABLE,SUPPORTS,J. R. R. Tolkien created Gimli.,"[[[28359, 34669, Gimli_-LRB-Middle-earth-RRB-,...",145447,"[{'doc_id': 'Gimli_-LRB-Middle-earth-RRB-', 't...",145447,SUPPORTS
145448,152180,VERIFIABLE,SUPPORTS,Susan Sarandon is an award winner.,"[[[176133, 189101, Susan_Sarandon, 1]], [[1761...",17244,"[{'doc_id': 'Stepmom_-LRB-film-RRB-', 'text': ...",17244,SUPPORTS

In [44]:
merged_df['claim'].dropna()

0         Nikolaj Coster-Waldau worked with the Fox Broa...
1                        Roman Atwood is a content creator.
2         History of art includes architecture, dance, s...
3                         Adrienne Bailon is an accountant.
4              System of a Down briefly disbanded in limbo.
                                ...
145444    Led Zeppelin released an eponymous debut album...
145445                                   Taal was romantic.
145446              Her stars American actress Rooney Mara.
145447                      J. R. R. Tolkien created Gimli.
145448                   Susan Sarandon is an award winner.
Name: claim, Length: 145449, dtype: object

In [45]:
from sklearn.metrics import classification_report

clean_df = merged_df.dropna(subset=['classification'])
report = classification_report(clean_df['label'].to_list(), clean_df['classification'].to_list())

print(report)

                 precision    recall  f1-score   support

NOT ENOUGH INFO       0.47      0.38      0.42     35639
        REFUTES       0.51      0.42      0.46     29775
       SUPPORTS       0.75      0.86      0.80     80034

       accuracy                           0.65    145448
      macro avg       0.57      0.55      0.56    145448
   weighted avg       0.63      0.65      0.64    145448